"""Unique Drop Locations data - which boss target-farms which Unique.

No Qt imports here on purpose - kept independently testable, same
separation principle as builds/*.json vs. the interfaces that read them.

Sourcing (Season 15, current as of verification): the 12 Uniques already
present in this project's own build data (builds/*.json's gear.key_items,
originally sourced from real Mobalytics build guides) were re-verified
against Icy-Veins' Season 15 boss-farming guide and aoeah.com's
independent Season 15 boss-loot table (both current-season, dated
sources; agreement on every overlapping item). A further 18 well-known
Uniques with a confirmed target-farm boss were added from the same two
sources to make the catalog more useful.

Corrections made to this project's own prior build data: Temerity's slot
was inconsistently recorded as "Charm"/"Pants" across different builds -
confirmed as Pants by three independent sources here.

Never guessed: where a field could not be confirmed (a Unique with no
single specific target boss - it drops from the shared Lair Boss Mythic
pool instead - or a slot/class not independently verified this pass),
that field is literally "DATA UNAVAILABLE" rather than an invented value.
"confidence"/"sources" reflect how many independent current sources
agreed on that item's target-farm boss.
"""

UNIQUES: list[dict] = [
    {
        "name": "Moloch's Beating Flame",
        "class": "Warlock",
        "slot": "Amulet",
        "target_boss": "The Butcher",
        "boss_zone": "Nahantu, near Kurast Docks Waypoint",
        "key_required": "1x Greater Lair Key",
        "confidence": "High",
        "sources": 3,
        "notes": None,
    },
    {
        "name": "Harlequin Crest",
        "class": "All Classes",
        "slot": "Helm",
        "target_boss": "DATA UNAVAILABLE",
        "boss_zone": "DATA UNAVAILABLE",
        "key_required": "DATA UNAVAILABLE",
        "confidence": "Medium",
        "sources": 2,
        "notes": "Drops from the shared Mythic Unique pool from any Lair Boss, not one specific boss.",
    },
    {
        "name": "Elegy",
        "class": "Warlock",
        "slot": "Weapon (1H Sword)",
        "target_boss": "Lord Zir",
        "boss_zone": "Fractured Peaks, Darkened Way (Ancient's Seat), east of Kyovashad",
        "key_required": "1x Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Temerity",
        "class": "All Classes",
        "slot": "Pants",
        "target_boss": "Harbinger of Hatred",
        "boss_zone": "Nahantu, Harbinger's Den, south of Kurast Docks",
        "key_required": "1x Greater Lair Key",
        "confidence": "High",
        "sources": 3,
        "notes": "Slot corrected from this project's earlier build data (previously inconsistent Charm/Pants).",
    },
    {
        "name": "The Eightfold Idol",
        "class": "Warlock",
        "slot": "Ring",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure, SW of Kyovashad",
        "key_required": "1x Lair Key (via Nightmare Sigil, 9x Distilled Fear)",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Infernal Homunculus",
        "class": "Warlock",
        "slot": "Offhand",
        "target_boss": "Urivar",
        "boss_zone": "Nahantu, Fields of Judgement, west of Kichuk",
        "key_required": "1x Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Fists of Fate",
        "class": "Warlock / Paladin",
        "slot": "Gloves",
        "target_boss": "DATA UNAVAILABLE",
        "boss_zone": "DATA UNAVAILABLE",
        "key_required": "DATA UNAVAILABLE",
        "confidence": "Medium",
        "sources": 1,
        "notes": "Drops from the general Lair Boss Mythic pool, not one specific boss.",
    },
    {
        "name": "Raiment of the Sea",
        "class": "Sorcerer",
        "slot": "DATA UNAVAILABLE",
        "target_boss": "Echo of Varshan",
        "boss_zone": "Hawezar, Malignant Burrow, near Tree of Whispers Waypoint",
        "key_required": "Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Galvanic Azurite",
        "class": "Sorcerer",
        "slot": "DATA UNAVAILABLE",
        "target_boss": "Duriel, King of Maggots",
        "boss_zone": "Kehjistan, Gaping Crevasse, east of Gea Kul",
        "key_required": "1x Greater Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": "Likely a Charm slot, not independently confirmed.",
    },
    {
        "name": "Light's Rebuke",
        "class": "Paladin",
        "slot": "Weapon",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure",
        "key_required": "1x Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Ring of the Ravenous",
        "class": "Barbarian",
        "slot": "Ring",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure",
        "key_required": "1x Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Red Sermon",
        "class": "Paladin",
        "slot": "Weapon (2H Sword)",
        "target_boss": "The Butcher",
        "boss_zone": "Nahantu, near Kurast Docks Waypoint",
        "key_required": "1x Greater Lair Key",
        "confidence": "High",
        "sources": 2,
        "notes": None,
    },
    {
        "name": "Windforce",
        "class": "DATA UNAVAILABLE",
        "slot": "Bow",
        "target_boss": "Urivar",
        "boss_zone": "Nahantu, Fields of Judgement",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Yen's Blessing",
        "class": "DATA UNAVAILABLE",
        "slot": "DATA UNAVAILABLE",
        "target_boss": "Urivar",
        "boss_zone": "Nahantu, Fields of Judgement",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Gohr's Devastating Grips",
        "class": "Barbarian",
        "slot": "Gloves",
        "target_boss": "Grigoire, The Galvanic Saint",
        "boss_zone": "Dry Steppes, Hall of the Penitent, south of Ked Bardu",
        "key_required": "Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Paingorger's Gauntlets",
        "class": "DATA UNAVAILABLE",
        "slot": "Gloves",
        "target_boss": "Grigoire, The Galvanic Saint",
        "boss_zone": "Dry Steppes, Hall of the Penitent",
        "key_required": "Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Orphan Maker",
        "class": "DATA UNAVAILABLE",
        "slot": "Weapon",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Starfall Coronet",
        "class": "DATA UNAVAILABLE",
        "slot": "Helm",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Eaglehorn",
        "class": "DATA UNAVAILABLE",
        "slot": "Bow",
        "target_boss": "Echo of Varshan",
        "boss_zone": "Hawezar, Malignant Burrow",
        "key_required": "Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Greatstaff of the Crone",
        "class": "Druid",
        "slot": "Weapon",
        "target_boss": "Echo of Varshan",
        "boss_zone": "Hawezar, Malignant Burrow",
        "key_required": "Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Skyhunter",
        "class": "DATA UNAVAILABLE",
        "slot": "Bow",
        "target_boss": "Lord Zir",
        "boss_zone": "Fractured Peaks, Darkened Way",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Fang of the Vipermagi",
        "class": "Sorcerer",
        "slot": "Weapon",
        "target_boss": "Lord Zir",
        "boss_zone": "Fractured Peaks, Darkened Way",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Rimeblood",
        "class": "DATA UNAVAILABLE",
        "slot": "DATA UNAVAILABLE",
        "target_boss": "Lord Zir",
        "boss_zone": "Fractured Peaks, Darkened Way",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Tal Rasha's Iridescent Loop",
        "class": "Sorcerer",
        "slot": "Ring",
        "target_boss": "Harbinger of Hatred",
        "boss_zone": "Nahantu, Harbinger's Den",
        "key_required": "1x Greater Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Mace of King Leoric",
        "class": "Necromancer",
        "slot": "Weapon",
        "target_boss": "The Butcher",
        "boss_zone": "Nahantu, Kurast Docks",
        "key_required": "1x Greater Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Godslayer Crown",
        "class": "DATA UNAVAILABLE",
        "slot": "Helm",
        "target_boss": "Echo of Andariel",
        "boss_zone": "Kehjistan, Hanged Man's Hall, east of Tarsarak",
        "key_required": "Greater Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Deathless Visage",
        "class": "DATA UNAVAILABLE",
        "slot": "Helm",
        "target_boss": "The Beast in the Ice",
        "boss_zone": "Fractured Peaks, Glacial Fissure",
        "key_required": "1x Lair Key",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Azurewrath",
        "class": "Paladin",
        "slot": "Weapon",
        "target_boss": "Bartuc, Lord of Chaos",
        "boss_zone": "Kehjistan, near Yshari Sanctum Waypoint (Infernal Hordes)",
        "key_required": "1x Infernal Hordes Compass + 666 Burning Aether",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Grasp of Shadow",
        "class": "Rogue",
        "slot": "Gloves",
        "target_boss": "Bartuc, Lord of Chaos",
        "boss_zone": "Kehjistan, Yshari Sanctum area",
        "key_required": "Infernal Hordes Compass",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
    {
        "name": "Griswold's Opus",
        "class": "DATA UNAVAILABLE",
        "slot": "Chest",
        "target_boss": "Astaroth",
        "boss_zone": "Scosglen, Cerrigar, end of Escalating Nightmares",
        "key_required": "1x Escalation Sigil",
        "confidence": "Medium",
        "sources": 1,
        "notes": None,
    },
]
