"""Unique item database for the Unique Drop Locations page.

No Qt imports here on purpose - kept independently testable, same
separation principle as builds/*.json vs. the interfaces that read them.

Sourcing (Season 15, current as of verification): the 12 Uniques already
present in this project's own build data (builds/*.json's gear.key_items,
originally sourced from real Mobalytics build guides) were re-verified
against Icy-Veins' Season 15 boss-farming guide and aoeah.com's
independent Season 15 boss-loot table. A further 18 well-known Uniques
with a confirmed target-farm boss were added from the same sources, then
cross-checked again against purediablo.com/sportskeeda/Game8 for every
class/slot field that was still unresolved after the first pass -
several corrections came out of that second pass (see per-item
``notes``), e.g. Yen's Blessing and Paingorger's Gauntlets' target boss
were both wrong in the first pass and are now corrected.

Harlequin Crest and Fists of Fate: Season 15's "Iconic Mythic" crafting
rework (Patch 3.2.0) means most Mythics are obtained by crafting a
regular Unique up via the Horadric Cube rather than a guaranteed boss
drop - see each item's own ``notes`` for its specific acquisition path.

``id`` is this project's own stable key (snake_case of the name) - used
by src/boss_data.py and src/unique_drop_service.py, never the item's
display name, so a future rename/typo fix never breaks a reference.
``target_bosses`` is a list of boss ids from src/boss_data.py; an empty
list means the item drops from a shared/general pool rather than one
specific boss (see ``notes``) - this is the single source of truth for
the Unique<->Boss relationship, src/boss_data.py never repeats it.

Corrections made to this project's own prior build data: Temerity's slot
was inconsistently recorded as "Charm"/"Pants" across different builds -
confirmed as Pants by three independent sources here.

Never guessed: where a field could not be confirmed, that field is
literally "DATA UNAVAILABLE" rather than an invented value. ``image`` is
None for every item today - no source with a documented, distributable
reuse license for Diablo IV item icon art was found (see
PROJECT_ROADMAP.md/commit history for the research); the UI shows a
neutral placeholder rather than treating this as blocking the rest of
the record.
"""

UNIQUES: list[dict] = [
    {
        "id": "molochs_beating_flame",
        "name": "Moloch's Beating Flame",
        "type": "Unique",
        "class": "Warlock",
        "slot": "Amulet",
        "target_bosses": ["the_butcher"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com, DiabloFilter",
        "confidence": "High",
        "sources_count": 3,
        "notes": None,
    },
    {
        "id": "harlequin_crest",
        "name": "Harlequin Crest",
        "type": "Mythic Unique",
        "class": "All Classes",
        "slot": "Helm",
        "target_bosses": [],
        "description": None,
        "image": None,
        "source": "Hardcore Gamer, Wowhead, aoeah.com",
        "confidence": "Medium",
        "sources_count": 3,
        "notes": (
            "Season 15's Iconic Mythic crafting: obtain the regular Unique version first, "
            "then upgrade it to Mythic via the Horadric Cube. Echo of Mephisto (see boss list) "
            "guarantees one Mythic item per kill from the general Mythic pool - not specifically "
            "this item."
        ),
    },
    {
        "id": "elegy",
        "name": "Elegy",
        "type": "Unique",
        "class": "Warlock",
        "slot": "Weapon (1H Sword)",
        "target_bosses": ["lord_zir"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "temerity",
        "name": "Temerity",
        "type": "Unique",
        "class": "All Classes",
        "slot": "Pants",
        "target_bosses": ["harbinger_of_hatred"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com, Game8",
        "confidence": "High",
        "sources_count": 3,
        "notes": "Slot corrected from this project's earlier build data (previously inconsistent Charm/Pants).",
    },
    {
        "id": "eightfold_idol",
        "name": "The Eightfold Idol",
        "type": "Unique",
        "class": "Warlock",
        "slot": "Ring",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": "Key requires a Nightmare Sigil (9x Distilled Fear) rather than a plain Lair Key.",
    },
    {
        "id": "infernal_homunculus",
        "name": "Infernal Homunculus",
        "type": "Unique",
        "class": "Warlock",
        "slot": "Offhand",
        "target_bosses": ["urivar"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "fists_of_fate",
        "name": "Fists of Fate",
        "type": "Mythic Unique",
        "class": "Warlock / Paladin",
        "slot": "Gloves",
        "target_bosses": [],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": (
            "Not a boss drop: obtained from Helltide Mystery Chests (opened with Cinders) or via "
            "a Horadric Cube 'Upgrade to Unique' craft."
        ),
    },
    {
        "id": "raiment_of_the_sea",
        "name": "Raiment of the Sea",
        "type": "Mythic Unique",
        "class": "Sorcerer",
        "slot": "Chest Armor",
        "target_bosses": ["echo_of_varshan"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "galvanic_azurite",
        "name": "Galvanic Azurite",
        "type": "Mythic Unique",
        "class": "Sorcerer",
        "slot": "Ring",
        "target_bosses": ["harbinger_of_hatred", "echo_of_andariel"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com, purediablo.com",
        "confidence": "High",
        "sources_count": 3,
        "notes": None,
    },
    {
        "id": "lights_rebuke",
        "name": "Light's Rebuke",
        "type": "Unique",
        "class": "Paladin",
        "slot": "Weapon",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "ring_of_the_ravenous",
        "name": "Ring of the Ravenous",
        "type": "Unique",
        "class": "Barbarian",
        "slot": "Ring",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "red_sermon",
        "name": "Red Sermon",
        "type": "Unique",
        "class": "Paladin",
        "slot": "Weapon (2H Sword)",
        "target_bosses": ["the_butcher"],
        "description": None,
        "image": None,
        "source": "Icy-Veins, aoeah.com",
        "confidence": "High",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "windforce",
        "name": "Windforce",
        "type": "Unique",
        "class": "Rogue",
        "slot": "Bow",
        "target_bosses": ["urivar"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "yens_blessing",
        "name": "Yen's Blessing",
        "type": "Unique",
        "class": "All Classes",
        "slot": "Boots",
        "target_bosses": ["lord_zir"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": "Target boss corrected from an earlier pass (was Urivar) - confirmed as Lord Zir.",
    },
    {
        "id": "gohrs_devastating_grips",
        "name": "Gohr's Devastating Grips",
        "type": "Unique",
        "class": "Barbarian",
        "slot": "Gloves",
        "target_bosses": ["grigoire"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "paingorgers_gauntlets",
        "name": "Paingorger's Gauntlets",
        "type": "Unique",
        "class": "All Classes",
        "slot": "Gloves",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": "Target boss corrected from an earlier pass (was Grigoire) - confirmed as The Beast in the Ice.",
    },
    {
        "id": "orphan_maker",
        "name": "Orphan Maker",
        "type": "Unique",
        "class": "Rogue",
        "slot": "Weapon (2H Crossbow)",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "starfall_coronet",
        "name": "Starfall Coronet",
        "type": "Unique",
        "class": "Sorcerer",
        "slot": "Helm",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "eaglehorn",
        "name": "Eaglehorn",
        "type": "Unique",
        "class": "Rogue",
        "slot": "Bow",
        "target_bosses": ["echo_of_varshan"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "greatstaff_of_the_crone",
        "name": "Greatstaff of the Crone",
        "type": "Unique",
        "class": "Druid",
        "slot": "Weapon",
        "target_bosses": ["echo_of_varshan"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "skyhunter",
        "name": "Skyhunter",
        "type": "Unique",
        "class": "Rogue",
        "slot": "Bow",
        "target_bosses": ["lord_zir"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "fang_of_the_vipermagi",
        "name": "Fang of the Vipermagi",
        "type": "Unique",
        "class": "Sorcerer",
        "slot": "Weapon",
        "target_bosses": ["lord_zir"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "rimeblood",
        "name": "Rimeblood",
        "type": "Unique",
        "class": "Sorcerer",
        "slot": "Gloves",
        "target_bosses": ["lord_zir"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "tal_rashas_iridescent_loop",
        "name": "Tal Rasha's Iridescent Loop",
        "type": "Unique",
        "class": "Sorcerer",
        "slot": "Ring",
        "target_bosses": ["harbinger_of_hatred"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "mace_of_king_leoric",
        "name": "Mace of King Leoric",
        "type": "Unique",
        "class": "Necromancer",
        "slot": "Weapon",
        "target_bosses": ["the_butcher"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "godslayer_crown",
        "name": "Godslayer Crown",
        "type": "Unique",
        "class": "All Classes",
        "slot": "Helm",
        "target_bosses": ["echo_of_andariel"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "deathless_visage",
        "name": "Deathless Visage",
        "type": "Unique",
        "class": "Necromancer",
        "slot": "Helm",
        "target_bosses": ["the_beast_in_the_ice"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
    {
        "id": "azurewrath",
        "name": "Azurewrath",
        "type": "Unique",
        "class": "Paladin",
        "slot": "Weapon",
        "target_bosses": ["bartuc_lord_of_chaos"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "grasp_of_shadow",
        "name": "Grasp of Shadow",
        "type": "Unique",
        "class": "Rogue",
        "slot": "Gloves",
        "target_bosses": ["bartuc_lord_of_chaos"],
        "description": None,
        "image": None,
        "source": "aoeah.com",
        "confidence": "Medium",
        "sources_count": 1,
        "notes": None,
    },
    {
        "id": "griswolds_opus",
        "name": "Griswold's Opus",
        "type": "Unique",
        "class": "Paladin",
        "slot": "Weapon (1H Sword)",
        "target_bosses": ["astaroth"],
        "description": None,
        "image": None,
        "source": "aoeah.com, purediablo.com",
        "confidence": "Medium",
        "sources_count": 2,
        "notes": None,
    },
]
